### ISSUE TITLE
lib.rs missing ptr module?

### ISSUE THREAD

**Issue by dsvensson** [shepmaster/rust-arduino-blink-led-no-core-with-cargo#1]
Tried building this with AVR enabled rust, but I get the following error:

```
error[E0583]: file not found for module `ptr`
  --> src/lib.rs:33:9
   |
33 | pub mod ptr;
   |         ^^^
   |
   = help: name the file either ptr.rs or ptr/mod.rs inside the directory "src"

error: aborting due to previous error

error: Could not compile `avr-core`.

```

**Comment by milada-horakova** [comment]
i suspect this example doesn't reflect recent changes to avr-rust.

i commented out this particular line in avr-core's lib.rs and have no clue if this was a bad idea. anyways it started to miss a drop_in_place language feature then so i added these lines i found somewhere in libcore. no clue how this feature works but at least it compiles.
these are my last lines in avr-core's lib.rs now:
```
//pub mod ptr;
use marker::Sized;

/// Executes the destructor (if any) of the pointed-to value.
///
/// This has two use cases:
///
/// * It is *required* to use `drop_in_place` to drop unsized types like
///   trait objects, because they can't be read out onto the stack and
///   dropped normally.
///
/// * It is friendlier to the optimizer to do this over `ptr::read` when
///   dropping manually allocated memory (e.g. when writing Box/Rc/Vec),
///   as the compiler doesn't need to prove that it's sound to elide the
///   copy.
///
/// # Undefined Behavior
///
/// This has all the same safety problems as `ptr::read` with respect to
/// invalid pointers, types, and double drops.
#[lang="drop_in_place"]
#[allow(unconditional_recursion)]
pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
    // Code here does not matter - this is replaced by the
    // real drop glue by the compiler.
    drop_in_place(to_drop);
}
```
no luck so far, couldn't even turn pinb5 led on. here is my branch containing also the hex file: 
[rust-arduino-blink-led-no-core-with-cargo.zip](https://github.com/shepmaster/rust-arduino-blink-led-no-core-with-cargo/files/1133741/rust-arduino-blink-led-no-core-with-cargo.zip)
 maybe someone can point me on the reason why my mcu isn't doing anyting.

i suspect either:
* incompatible old core code with new compiler
* i have a different mcu (atmega2560) - already verified that i/o references are the same, didn't check the interrupt vector yet.
* i am running avr-rust in lxss (ubuntu for win10)
or likely a combination of all these issues 

is there another approach to start with?

**Comment by milada-horakova** [comment]
update: my version is working if i build it for and flash an atmega328p. don't know what my problem is on atmega2560...

**Comment by milada-horakova** [comment]
update: my version is working if i build it for and flash an atmega328p. don't know what's the problem with my atmega2560.

**Comment by shepmaster** [comment]
Yeah, mismatched versions is highly likely. We are working on getting the "real" libcore able to compile. See the (now closed) avr-rust/rust#54 and another project with a forked libcore (https://github.com/gergoerdi/rust-avr-libcore-mini). There's no CI on this repo to keep me honest 😈

**Comment by shepmaster** [comment]
I went ahead and switched to using libcore-mini as it's a bit newer and closer in sync to the version of Rust (and we really want to get the real libcore Any Day Now ™ ).

I was able to compile this code and flash the board using avr-rust/rust@897020690cab72e17280af259dfc310b17aa49cc.

**Comment by milada-horakova** [comment]
finally!
found out that arduino mega has it's led on pinb7, so the mcu actually runs the program. another issue was that atmega2560's interrupt vector is quite different. i changed the interrupt_vector.S in this now-working version: [rust-arduino-blink-led-no-core-with-cargo_atmega2560.zip](https://github.com/shepmaster/rust-arduino-blink-led-no-core-with-cargo/files/1133890/rust-arduino-blink-led-no-core-with-cargo_atmega2560.zip) based on 2560's datasheet.

are there problems with interrupt vectors in the toolchain or why do we need to explicitly supply them?

**Comment by shepmaster** [comment]
> atmega2560's interrupt vector is quite different.

That is is. It appears that the 2560 is a drastically more capable chip — 6 timers and 4 UARTs? That
 CPU is on 🔥.


> are there problems with interrupt vectors in the toolchain or why do we need to explicitly supply them?

Well... the word "toolchain" is an interesting one! My approach so far has been to try to eschew as much of the existing toolchain as possible. I want basically everything to be written in either Rust or AVR assembly and to be present within this repository (or a collection of "our" repositories).

That's why you see mention of the interrupt vector at all. My *guess* is that one of your interrupts was actually firing and triggering the corresponding routine. However, that routine wasn't set properly because the previous IVR was too small, so who knows what code was actually being called!

When you filled out the full IVR, then triggering that interrupt no longer caused the same problem.

**Comment by shepmaster** [comment]
We've updated avr-rust to LLVM 8 and a newer rust version, which should include `core::ptr`
